import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

// Precache all static assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache API calls (adjust the URL to your API endpoint)
registerRoute(
  ({ url }) => url.origin === 'https://blur-api-ruby.vercel.app/api',
  // ({ url }) => url.origin === 'http://localhost:5000/api',
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
  })
);