apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: "2401106"
spec:
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000
  type: NodePort
